[build]
builder = "maven"

[deploy]
startCommand = "java -jar target/itaiJavaPlay-0.0.1-SNAPSHOT.jar"

[[services]]
name = "itaiJavaPlay"

[services.variables]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
